#!/usr/bin/env bash
#
# Downloading Arch ISOFile(s)
#
#

# Mirror (Umeå, Swe)
_mirror='https://ftp.acc.umu.se';


# Vars
_dir=$(date "+%Y-%m-${1:-01}");
_iso='archlinux-'$(echo ${_dir//-/.})'-x86_64';

# Make directory
mkdir -pv "${_dir}" && cd "${_dir}";

# Download from mirror
for f in iso.sig iso; do
	wget ${_mirror}/mirror/archlinux/iso/latest/"${_iso}.${f}";
done

# Get the SHA1sums as well
wget ${_mirror}/mirror/archlinux/iso/latest/sha1sums.txt;

# Verify the signature (sig file)
if [[ `type gpg 2>/dev/null` ]]; then
	gpg2 --verify "${_iso}.iso.sig" "${_iso}.iso";
else
	echo "Couldn't find 'gpg'. Please verify the signature.";
fi
