#!/usr/bin/env bash
#
# /usr/local/xbin/encFile
#
# Description: Encrypt or Decrypt files w openssl
#
# ------------------------------------------------------------
#
# Usage:
#   Encrypt: encFile [bf|aes] <file> (default: bf)
#   Decrypt: encFile <file>
#

if [[ $1 =~ ^bf$|^aes$ ]]; then
    _c=$1;
    shift 1;
fi

# Vars
_file="$1";
_basename=$(basename $0);
[ -z ${_c} ] && _c='bf';
[[ ${_file##*.} == 'bf' ]] && _enc='bf';
[[ ${_file##*.} == 'aes' ]] && _enc='aes256';

# Usage
function __err()
{
    cat <<INFO
Usage:
  Encrypt: ${_basename} [bf|aes] <file> (default: bf)
  Decrypt: ${_basename} <file>

INFO
}

if [[ $# < 1 ]]; then
    __err && exit 1;
elif [ -d "${_file}" ] || [ ! -f "${_file}" ]; then
    echo -e "\"${_file}\" is not a valid or existing file.\n";
    __err && exit 1;
fi

# Encrypt
if [[ -n ${_c} && -z ${_enc} ]]; then
    [ ${_c} == 'aes' ] && _c='aes256';
    openssl enc -${_c} -A -in "${_file}" > "${_file}.${_c//256/}";

# Decrypt
else
    openssl enc -${_enc} -A -d -in "${_file}" > "${_file%.*}";
fi