#!/usr/bin/env bash
#
# /usr/local/xbin/extract
#
#
# Decription: Script to extract misc archives
#
# Usage:
#     extract <archive> ...
#     extract fooBar.tar.xz
#     extract fooBar.tar.xz barBaz.tar.xz
#     extract ./**/*.tar.xz
#

# Help
[[ $# < 1 || $1 == '-h' ]] && cat $0 | sed -n '8,12p' && exit 1;

# Vars
ERR=0;

for f in "$@"; do
    _dir=$(dirname "${f}");
    _file=$(basename "${f}");
    _ext="${_file#*.}";

    if [ -f "${f}" ]; then
        case "${f}" in
            *.tar.bz2 | *.tbz2) tar -jxvf "${f}" -C "${_dir}";  ;;
            *.tar.xz) tar -xvf "${f}" -C "${_dir}";             ;;
            *.tar.gz | *.tgz) tar -zxvf "${f}" -C "${_dir}";    ;;
            *.bz2) bunzip2 -kf "${f}";                          ;;
            *.rar) (cd "${_dir}" && unrar x "${f}");            ;;
            *.gz) gunzip -kvf "${f}";                           ;;
            *.tar) tar -xf "${f}" -C "${_dir}";                 ;;
            *.zip) unzip "${f}" -d "${_dir}";                   ;;
            *.Z) (cd "${_dir}" && uncompress "${f}");           ;;
            *.7z) (cd "${_dir}" && 7za x "${f}");               ;;
            *)
                echo "$(basename $0): '${_file}' cannot be extracted. '${_ext}' is not supported.";
                ERR=1;
                ;;
        esac
    else
        echo "'${_file}' is not a valid file";
        ERR=1;
    fi
done

exit ${ERR};
