#!/usr/bin/env bash
# ------------------------------------------------------------------
#
# /usr/local/xbin/ezip1
#
# Simple shellscript to zip files from Terminal, leaving
# certain files alone. (Handles only 1 folder).
#
#
_folder=`basename "$1"`;
_path=`dirname "$1"`;

# Zip it...
cd "$_path";
zip -r -o "$_folder".zip "$_folder" -x "*.DS_*" "*__MACOSX*" "*.Trashes*" "*_notes*" "*.git*" "*.svn*" "*error_log*" "*._*";
say zip\'d;
