#!/usr/bin/env bash
#
# /usr/local/xbin
#
# Description: # Script to convert OS X .webloc's into Linux .desktop files
#
# Disclainer: You use this script AT YOUR OWN RISK, and it comes with NO WARRANTY.
# It's been made for my own personal use.
#

# Put a log in current directory of the ones who didn't make it.
dtLog='./'$(basename $0)'_log.txt';

echo -e "/* These \"weblocs\" didn't convert into \".desktop\" */\n\n- - -\n\n" > "${dtLog}";

# Find all weblocs...
find . -name "*.webloc" | while read _file; do

	# Clean up names (:/ -> -). More chars?
	cleanUp=`basename "$(echo "${_file}")" | sed 's/[\/\:]/\-/g'`;

	# cleaning any xtra ":" just in case. "/" displays as ":" in Terminal.
	fileOut=`dirname "$(echo "${_file}")/${cleanUp}" | sed 's/[\:]/\-/g'`;

	# New extension
	dtFile=`echo "${fileOut}" | sed 's/webloc/desktop/'`;
	dtName=`basename "${fileOut}" | sed 's/.webloc//'`;

	# make sure the file(s) are XML, and get the url
	plutil -convert xml1 "${_file}";
	dtUrl=`cat "${_file}" | grep -i '<string>.*<\/string>' | sed 's/^.*<string>//;s/<\/string>$//'` 2> /dev/null;

	# Having some old ones where they are in "/rsrc"... Try DeRez before dumping them to the log.
	if [[ -z "${dtUrl}" ]] ; then
		dtUrl=`DeRez -e -only url "${_file}" | sed -e 's/.*\/\* \(.*\) \*\//\1/' | sed -e :a -e '$!N; s/\n//; ta' -e 's/^.*{\(.*\)};/\1/'`;
	fi

	# Pass path/filename to logfile if it fails.
	if [[ -z "${dtUrl}" ]] ; then
		echo "${_file}" >> "${dtLog}";
	else

		# Just follow the freedesktop standard...
		cat << WEBLOC > "${dtFile}"
[Desktop Entry]
Encoding=UTF-8
Type=Link
Icon=text-html
Name=$dtName
URL=$dtUrl
WEBLOC

		# Delete the webloc fileOut
		echo -n 'Deleting: ';
		rm -v "${_file}";
	fi
done

# Add date to the log
echo -e "\n\n" >> "${dtLog}";
date "+Log created: %F at %X" >> "${dtLog}";

# Reveal the logfile in Finder
open -R ${dtLog};
