#!/usr/bin/env bash
#
# /usr/local/xbin/mkpwd
#
#
# Description:
#     Simple password generator to create strong random passwords.
#     Default size/length is 20, and minimum is 16.
#
# Usage:
#     mkpwd [ -h ] [ size ] [ nr of pwd ]
#     mkpwd          20 character pwd
#     mkpwd 32       32 character pwd
#     mkpwd 24 10    10x 24-character pwds
#

PWD_LENGTH=20;
MIN_LENGTH=16;

# Help
[[ ${1} == '-h' ]] && sed -n '10,15p' ${0} && exit 1;

# Min 16 chars (default: 20)
[[ -n "${1}" && "${1}" -le ${MIN_LENGTH} ]] && _size=${MIN_LENGTH} || _size="${1}";

if [ ${#} -gt 1 ]; then
    echo -e ":: Generating ${2} ${_size:-${PWD_LENGTH}}-character passwords\n";
fi

for ((n=0; n < ${2:-1}; n++)); do
    LC_ALL=C \
        tr -cd 'a-zA-Z0-9!"#$%&'\''()*+,-./:;£¢<=>?@[\]^_{|}~' \
        < /dev/urandom | head -c ${_size:-${PWD_LENGTH}};
        echo;
done

[ ${#} -gt 1 ] && echo || exit 0;

exit;
