#!/usr/bin/env bash
#
# /usr/local/xbin/mktar
#

# Check $1 for extension
# xz = default, with fallback on gz if not installed
# ------------------------------------------------------------
[[ `type xz 2>/dev/null` ]] && _xz='xz' || _xz='gz'
[[ ! -d $1 && ! -f $1 ]] && _ext=$1 && shift || _ext=${_xz};


# Vars
# ------------------------------------------------------------
ERR=0;
_base=$(basename $0);
_path=$(dirname "$1");
_dir=$(basename "$1");
_excludes=`echo --exclude={'.DS_Store','._*'}`;

if [ -e "$1" ]; then
    cd "${_path}";
    case $_ext in
        gz)
            tar -cvzf "${_dir}".tar.${_ext} ${_excludes} "${_dir}";
            ;;
        bz2)
            tar -cvjf "${_dir}".tar.${_ext} ${_excludes} "${_dir}";
            ;;
        xz)
            tar -cvf - ${_excludes} "${_dir}" | xz -6e > "${_dir}".tar.${_ext};
            ;;
        *)
            echo -e ":: ${_base}: Could not create '${_dir}.tar.${_ext}'\n";
            ERR=1;
            ;;
    esac
else
    echo -e ":: '${_dir}' is not a valid file/directory\n";
    ERR=1;
fi

[[ ${ERR} != 0 ]] && cat  <<INFO
Usage: ${_base} [gz | bz2 | xz] [files | directories]
       ${_base} foobar.d        # -> foobar.d.tar.xz
       ${_base} gz foobar.d     # -> foobar.d.tar.gz

INFO

exit ${ERR};
