#!/usr/bin/env bash
#
# /usr/local/xbin/mktar
#

# Check $1 for extension
# xz = default, with fallback on gz if not installed
# ------------------------------------------------------------
[[ `type xz 2>/dev/null` ]] && _xz='xz' || _xz='gz';
[[ ${1} =~ ^xz$|^bz2$|^gz$ ]] && _ext=$1 && shift 1 || _ext=${_xz};
[[ ! `type xz 2>/dev/null` && ${_ext} == 'xz' ]] && _ext='gz';


# Vars
# ------------------------------------------------------------
ERR=0;
_base=$(basename $0);
_path=$(dirname "$1");
_dir=$(basename "$1");
_excludes=`echo --exclude={'.DS_Store','._*'}`;

if [ -e "$1" ]; then
    cd "${_path}";
    case $_ext in
        gz)
            tar -cvzf "${_dir}".tar.${_ext} ${_excludes} "${_dir}";
            ;;
        bz2)
            tar -cvjf "${_dir}".tar.${_ext} ${_excludes} "${_dir}";
            ;;
        xz)
            tar -cvf - ${_excludes} "${_dir}" | xz -6e > "${_dir}".tar.${_ext};
            ;;
        *|-h)
            echo -e ":: ${_base}: Could not create '${_dir}.tar.${_ext}'\n";
            ERR=1;
            ;;
    esac
else
    echo -e ":: '${_dir}' is not a valid file/directory\n";
    ERR=1;
fi

[[ ${ERR} != 0 ]] && cat  <<INFO
Usage: ${_base} [ gz | bz2 | xz ] [ file | directory ]
       ${_base} foobar.d          # -> foobar.d.tar.xz
       ${_base} gz foobar.d       # -> foobar.d.tar.gz

INFO

exit ${ERR};
