#!/usr/bin/env bash
#
# /usr/local/xbin
#
# Description:
# Create thumbnails/miniatures.
# Thumb (defaults) to 250px. Max 500.
#
# Script is using 'convert' (ImageMagick).
# On OS X, it uses 'convert' if installed with a fallback on 'sips' (bundled).
#
# Usage:
#   mkthumb file.jpg         Result: file_250px.jpg
#   mkthumb file.jpg 400     Result: file_400px.jpg
#   mkthumb -h               Show help
#

ERR=0

# Help
[[ $1 == '-h' ]] && cat $0 | sed -n '12,15p' && exit 1;

[[ $2 && $2 -lt 501 ]] && _px=$2 || _px=250;
_file=$(basename "$1");
_ext=$(echo "${_file##*.}");

if [[ `uname` == 'Darwin' ]]; then
    # IMv7
    if [[ `type magick 2> /dev/null` ]]; then
        magick "$1" -resize ${_px}x${_px} -quality 100 "${1%.*}_${_px}px.${_ext}";
        echo -e "$1\n  ${1%.*}_${_px}px.${_ext}";
    # IMv6
    elif [[ `type convert 2> /dev/null` ]]; then
        convert "$1" -resize ${_px}x${_px} -quality 100 "${1%.*}_${_px}px.${_ext}";
        echo -e "$1\n  ${1%.*}_${_px}px$_ext";
    else
        sips -Z ${_px} -s formatOptions best "$1" --out "${1%.*}_${_px}px$.${_ext}" 2> /dev/null;
    fi
    ERR=$?
else
    _msg="$FUNCNAME: Can't find 'magick' or 'convert'. Please install ImageMagick...";
    [[ ! `type magick 2> /dev/null` && ! `type convert 2> /dev/null` ]] && echo ${_msg} && return 1;
    # IMv7
    if [[ `type magick 2> /dev/null` ]]; then
        magick "$1" -resize ${_px}x${_px} -quality 100 "${1%.*}_${_px}px.${_ext}";
        echo -e "$1\n  ${1%.*}_${_px}px.${_ext}";
    # IMv6
    elif [[ `type convert 2> /dev/null` ]]; then
        convert "$1" -resize ${_px}x${_px} -quality 100 "${1%.*}_${_px}px.${_ext}";
        echo -e "$1\n  ${1%.*}_${_px}px.${_ext}";
    fi
    ERR=$?
fi

exit ${ERR};