#!/usr/bin/env bash
#
# /usr/local/xbin/toggle
#
# Description: Script to toggle things, like hidden files, desktop icons..
#

ERR=0

function toggleValue()
{
    local _item="$1";
    STATUS=$(defaults read com.apple.Finder ${_item});
    [ $STATUS == 1 ] && _bool=false || _bool=true;
    defaults write com.apple.Finder ${_item} -bool ${_bool};
    killall Finder;
}

case $1 in
    hidden)
        toggleValue "AppleShowAllFiles";
        ERR=$?;
        ;;
    desktop)
        toggleValue "CreateDesktop";
        ERR=$?;
        ;;
    *)  echo -e "Usage: $(basename $0) [ hidden | desktop ]\n";
        ERR=1
esac

exit ${ERR};
